name: pytest-bdd
channels:
  - conda-forge
  - defaults
  - auto
dependencies:
  - nodejs
  - conda-forge::pytest-bdd
  - anaconda::selenium
  - python=3.8
  - anaconda::flake8
  - anaconda::pylint
  - anaconda::pytest
  - conda-forge::uritools
  - pip
  - requests
  # - pip:
  